// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8bN2fhugKeuTZRBNXp81x9FFIkGWqAs',
    appId: '1:53239051223:android:a11cc09ff21287986dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7X5jqv0OpU0d8q9VztCWXuWgf2XOt6Dg',
    appId: '1:53239051223:ios:6ab7ab503377408e6dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
    androidClientId: '53239051223-1d6fmgs9344st4ca8svdugl00uukjou7.apps.googleusercontent.com',
    iosClientId: '53239051223-vgjah3p8p4eh9ijsj2sfrk5ivmkabnoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobalworld',
  );
}
